import logo from "./logo.svg";
import "./App.css";
import React from "react";
import { render } from "react-dom";
import { VictoryBar, VictoryChart, VictoryAxis } from "victory";

function App() {
  const clubData = [
    {
      Position: 23,
      Club: "FC Shakhtar Donetsk",
      Country: "UKR",
      Participated: 16,
      Titles: 0,
      Played: 106,
      Win: 35,
      Draw: 23,
      Loss: 48,
      "Goals For": 140,
      "Goals Against": 183,
      Pts: 93,
      "Goal Diff": -43,
    },
    {
      Position: 25,
      Club: "FC Dynamo Kyiv",
      Country: "UKR",
      Participated: 18,
      Titles: 0,
      Played: 121,
      Win: 30,
      Draw: 29,
      Loss: 62,
      "Goals For": 137,
      "Goals Against": 187,
      Pts: 89,
      "Goal Diff": -50,
    },
    {
      Position: 26,
      Club: "Galatasaray AŞ",
      Country: "TUR",
      Participated: 16,
      Titles: 0,
      Played: 116,
      Win: 28,
      Draw: 29,
      Loss: 59,
      "Goals For": 112,
      "Goals Against": 197,
      Pts: 85,
      "Goal Diff": -85,
    },
    {
      Position: 49,
      Club: "Beşiktaş JK",
      Country: "TUR",
      Participated: 8,
      Titles: 0,
      Played: 50,
      Win: 13,
      Draw: 9,
      Loss: 28,
      "Goals For": 46,
      "Goals Against": 102,
      Pts: 35,
      "Goal Diff": -56,
    },
    {
      Position: 55,
      Club: "Fenerbahçe SK",
      Country: "TUR",
      Participated: 6,
      Titles: 0,
      Played: 40,
      Win: 11,
      Draw: 6,
      Loss: 23,
      "Goals For": 42,
      "Goals Against": 70,
      Pts: 28,
      "Goal Diff": -28,
    },
    {
      Position: 98,
      Club: "Trabzonspor AŞ",
      Country: "TUR",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 4,
      Loss: 1,
      "Goals For": 3,
      "Goals Against": 5,
      Pts: 6,
      "Goal Diff": -2,
    },
    {
      Position: 133,
      Club: "İstanbul Başakşehir FK",
      Country: "TUR",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 0,
      Loss: 5,
      "Goals For": 7,
      "Goals Against": 18,
      Pts: 2,
      "Goal Diff": -11,
    },
    {
      Position: 140,
      Club: "Bursaspor SK",
      Country: "TUR",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 1,
      Loss: 5,
      "Goals For": 2,
      "Goals Against": 16,
      Pts: 1,
      "Goal Diff": -14,
    },
    {
      Position: 59,
      Club: "IFK Göteborg",
      Country: "SWE",
      Participated: 4,
      Titles: 0,
      Played: 26,
      Win: 10,
      Draw: 3,
      Loss: 13,
      "Goals For": 30,
      "Goals Against": 39,
      Pts: 23,
      "Goal Diff": -9,
    },
    {
      Position: 111,
      Club: "Malmö FF",
      Country: "SWE",
      Participated: 3,
      Titles: 0,
      Played: 18,
      Win: 2,
      Draw: 1,
      Loss: 15,
      "Goals For": 6,
      "Goals Against": 50,
      Pts: 5,
      "Goal Diff": -44,
    },
    {
      Position: 120,
      Club: "Helsingborgs IF",
      Country: "SWE",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 2,
      Loss: 3,
      "Goals For": 6,
      "Goals Against": 14,
      Pts: 4,
      "Goal Diff": -8,
    },
    {
      Position: 139,
      Club: "AIK",
      Country: "SWE",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 1,
      Loss: 5,
      "Goals For": 4,
      "Goals Against": 16,
      Pts: 1,
      "Goal Diff": -12,
    },
    {
      Position: 84,
      Club: "NK Maribor",
      Country: "SVN",
      Participated: 3,
      Titles: 0,
      Played: 18,
      Win: 1,
      Draw: 7,
      Loss: 10,
      "Goals For": 9,
      "Goals Against": 41,
      Pts: 9,
      "Goal Diff": -32,
    },
    {
      Position: 106,
      Club: "MFK Petržalka",
      Country: "SVK",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 3,
      Loss: 2,
      "Goals For": 5,
      "Goals Against": 9,
      Pts: 5,
      "Goal Diff": -4,
    },
    {
      Position: 143,
      Club: "MFK Košice",
      Country: "SVK",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 0,
      Loss: 6,
      "Goals For": 2,
      "Goals Against": 13,
      Pts: 0,
      "Goal Diff": -11,
    },
    {
      Position: 145,
      Club: "MŠK Žilina",
      Country: "SVK",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 0,
      Loss: 6,
      "Goals For": 3,
      "Goals Against": 19,
      Pts: 0,
      "Goal Diff": -16,
    },
    {
      Position: 37,
      Club: "FC Basel 1893",
      Country: "SUI",
      Participated: 8,
      Titles: 0,
      Played: 60,
      Win: 19,
      Draw: 13,
      Loss: 28,
      "Goals For": 68,
      "Goals Against": 107,
      Pts: 51,
      "Goal Diff": -39,
    },
    {
      Position: 85,
      Club: "Grasshopper Club Zürich",
      Country: "SUI",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 3,
      Draw: 2,
      Loss: 7,
      "Goals For": 11,
      "Goals Against": 18,
      Pts: 8,
      "Goal Diff": -7,
    },
    {
      Position: 96,
      Club: "BSC Young Boys",
      Country: "SUI",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 2,
      Draw: 3,
      Loss: 7,
      "Goals For": 11,
      "Goals Against": 24,
      Pts: 7,
      "Goal Diff": -13,
    },
    {
      Position: 124,
      Club: "FC Thun",
      Country: "SUI",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 1,
      Loss: 4,
      "Goals For": 4,
      "Goals Against": 9,
      Pts: 3,
      "Goal Diff": -5,
    },
    {
      Position: 126,
      Club: "FC Zürich",
      Country: "SUI",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 1,
      Loss: 4,
      "Goals For": 5,
      "Goals Against": 14,
      Pts: 3,
      "Goal Diff": -9,
    },
    {
      Position: 110,
      Club: "FK Crvena zvezda",
      Country: "SRB",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 2,
      Draw: 1,
      Loss: 9,
      "Goals For": 8,
      "Goals Against": 37,
      Pts: 5,
      "Goal Diff": -29,
    },
    {
      Position: 127,
      Club: "FK Partizan",
      Country: "SRB",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 0,
      Draw: 3,
      Loss: 9,
      "Goals For": 5,
      "Goals Against": 21,
      Pts: 3,
      "Goal Diff": -16,
    },
    {
      Position: 41,
      Club: "Rangers FC",
      Country: "SCO",
      Participated: 10,
      Titles: 0,
      Played: 62,
      Win: 12,
      Draw: 23,
      Loss: 27,
      "Goals For": 63,
      "Goals Against": 94,
      Pts: 47,
      "Goal Diff": -31,
    },
    {
      Position: 42,
      Club: "Celtic FC",
      Country: "SCO",
      Participated: 10,
      Titles: 0,
      Played: 66,
      Win: 18,
      Draw: 10,
      Loss: 38,
      "Goals For": 61,
      "Goals Against": 116,
      Pts: 46,
      "Goal Diff": -55,
    },
    {
      Position: 31,
      Club: "FC Spartak Moskva",
      Country: "RUS",
      Participated: 12,
      Titles: 0,
      Played: 80,
      Win: 22,
      Draw: 18,
      Loss: 40,
      "Goals For": 99,
      "Goals Against": 145,
      Pts: 62,
      "Goal Diff": -46,
    },
    {
      Position: 35,
      Club: "PFC CSKA Moskva",
      Country: "RUS",
      Participated: 12,
      Titles: 0,
      Played: 78,
      Win: 18,
      Draw: 18,
      Loss: 42,
      "Goals For": 82,
      "Goals Against": 131,
      Pts: 54,
      "Goal Diff": -49,
    },
    {
      Position: 38,
      Club: "FC Zenit",
      Country: "RUS",
      Participated: 9,
      Titles: 0,
      Played: 60,
      Win: 18,
      Draw: 14,
      Loss: 28,
      "Goals For": 68,
      "Goals Against": 86,
      Pts: 50,
      "Goal Diff": -18,
    },
    {
      Position: 56,
      Club: "FC Lokomotiv Moskva",
      Country: "RUS",
      Participated: 6,
      Titles: 0,
      Played: 44,
      Win: 9,
      Draw: 8,
      Loss: 27,
      "Goals For": 39,
      "Goals Against": 68,
      Pts: 26,
      "Goal Diff": -29,
    },
    {
      Position: 81,
      Club: "FC Rubin",
      Country: "RUS",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 2,
      Draw: 6,
      Loss: 4,
      "Goals For": 6,
      "Goals Against": 11,
      Pts: 10,
      "Goal Diff": -5,
    },
    {
      Position: 116,
      Club: "FC Krasnodar",
      Country: "RUS",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 2,
      Loss: 3,
      "Goals For": 6,
      "Goals Against": 11,
      Pts: 4,
      "Goal Diff": -5,
    },
    {
      Position: 118,
      Club: "FC Rostov",
      Country: "RUS",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 2,
      Loss: 3,
      "Goals For": 6,
      "Goals Against": 12,
      Pts: 4,
      "Goal Diff": -6,
    },
    {
      Position: 62,
      Club: "FCSB",
      Country: "ROU",
      Participated: 7,
      Titles: 0,
      Played: 42,
      Win: 4,
      Draw: 14,
      Loss: 24,
      "Goals For": 30,
      "Goals Against": 69,
      Pts: 22,
      "Goal Diff": -39,
    },
    {
      Position: 75,
      Club: "CFR 1907 Cluj",
      Country: "ROU",
      Participated: 3,
      Titles: 0,
      Played: 18,
      Win: 5,
      Draw: 3,
      Loss: 10,
      "Goals For": 20,
      "Goals Against": 28,
      Pts: 13,
      "Goal Diff": -8,
    },
    {
      Position: 97,
      Club: "FC Unirea Urziceni",
      Country: "ROU",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 2,
      Draw: 2,
      Loss: 2,
      "Goals For": 8,
      "Goals Against": 8,
      Pts: 6,
      "Goal Diff": 0,
    },
    {
      Position: 142,
      Club: "FC Oţelul Galaţi",
      Country: "ROU",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 0,
      Loss: 6,
      "Goals For": 3,
      "Goals Against": 11,
      Pts: 0,
      "Goal Diff": -8,
    },
    {
      Position: 7,
      Club: "FC Porto",
      Country: "POR",
      Participated: 25,
      Titles: 1,
      Played: 204,
      Win: 87,
      Draw: 49,
      Loss: 68,
      "Goals For": 272,
      "Goals Against": 240,
      Pts: 223,
      "Goal Diff": 32,
    },
    {
      Position: 19,
      Club: "SL Benfica",
      Country: "POR",
      Participated: 16,
      Titles: 0,
      Played: 112,
      Win: 39,
      Draw: 27,
      Loss: 46,
      "Goals For": 122,
      "Goals Against": 149,
      Pts: 105,
      "Goal Diff": -27,
    },
    {
      Position: 45,
      Club: "Sporting Clube de Portugal",
      Country: "POR",
      Participated: 9,
      Titles: 0,
      Played: 56,
      Win: 17,
      Draw: 8,
      Loss: 31,
      "Goals For": 74,
      "Goals Against": 101,
      Pts: 42,
      "Goal Diff": -27,
    },
    {
      Position: 74,
      Club: "Boavista FC",
      Country: "POR",
      Participated: 2,
      Titles: 0,
      Played: 18,
      Win: 4,
      Draw: 6,
      Loss: 8,
      "Goals For": 14,
      "Goals Against": 25,
      Pts: 14,
      "Goal Diff": -11,
    },
    {
      Position: 89,
      Club: "SC Braga",
      Country: "POR",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 4,
      Draw: 0,
      Loss: 8,
      "Goals For": 12,
      "Goals Against": 24,
      Pts: 8,
      "Goal Diff": -12,
    },
    {
      Position: 83,
      Club: "Legia Warszawa",
      Country: "POL",
      Participated: 2,
      Titles: 0,
      Played: 14,
      Win: 3,
      Draw: 3,
      Loss: 8,
      "Goals For": 14,
      "Goals Against": 35,
      Pts: 9,
      "Goal Diff": -21,
    },
    {
      Position: 123,
      Club: "RTS Widzew Łódź",
      Country: "POL",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 1,
      Loss: 4,
      "Goals For": 6,
      "Goals Against": 10,
      Pts: 3,
      "Goal Diff": -4,
    },
    {
      Position: 34,
      Club: "Rosenborg BK",
      Country: "NOR",
      Participated: 11,
      Titles: 0,
      Played: 74,
      Win: 19,
      Draw: 18,
      Loss: 37,
      "Goals For": 95,
      "Goals Against": 129,
      Pts: 56,
      "Goal Diff": -34,
    },
    {
      Position: 131,
      Club: "Molde FK",
      Country: "NOR",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 0,
      Loss: 5,
      "Goals For": 6,
      "Goals Against": 14,
      Pts: 2,
      "Goal Diff": -8,
    },
    {
      Position: 15,
      Club: "AFC Ajax",
      Country: "NED",
      Participated: 17,
      Titles: 1,
      Played: 132,
      Win: 56,
      Draw: 34,
      Loss: 42,
      "Goals For": 190,
      "Goals Against": 146,
      Pts: 146,
      "Goal Diff": 44,
    },
    {
      Position: 24,
      Club: "PSV Eindhoven",
      Country: "NED",
      Participated: 16,
      Titles: 0,
      Played: 110,
      Win: 33,
      Draw: 25,
      Loss: 52,
      "Goals For": 108,
      "Goals Against": 160,
      Pts: 91,
      "Goal Diff": -52,
    },
    {
      Position: 54,
      Club: "Feyenoord",
      Country: "NED",
      Participated: 5,
      Titles: 0,
      Played: 36,
      Win: 9,
      Draw: 11,
      Loss: 16,
      "Goals For": 38,
      "Goals Against": 59,
      Pts: 29,
      "Goal Diff": -21,
    },
    {
      Position: 104,
      Club: "FC Twente",
      Country: "NED",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 3,
      Loss: 2,
      "Goals For": 9,
      "Goals Against": 11,
      Pts: 5,
      "Goal Diff": -2,
    },
    {
      Position: 115,
      Club: "AZ Alkmaar",
      Country: "NED",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 4,
      Loss: 2,
      "Goals For": 4,
      "Goals Against": 8,
      Pts: 4,
      "Goal Diff": -4,
    },
    {
      Position: 125,
      Club: "sc Heerenveen",
      Country: "NED",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 1,
      Loss: 4,
      "Goals For": 3,
      "Goals Against": 9,
      Pts: 3,
      "Goal Diff": -6,
    },
    {
      Position: 130,
      Club: "Willem II",
      Country: "NED",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 2,
      Loss: 4,
      "Goals For": 7,
      "Goals Against": 15,
      Pts: 2,
      "Goal Diff": -8,
    },
    {
      Position: 105,
      Club: "FC Sheriff Tiraspol",
      Country: "MDA",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 2,
      Draw: 1,
      Loss: 3,
      "Goals For": 7,
      "Goals Against": 11,
      Pts: 5,
      "Goal Diff": -4,
    },
    {
      Position: 119,
      Club: "FC Astana",
      Country: "KAZ",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 4,
      Loss: 2,
      "Goals For": 5,
      "Goals Against": 11,
      Pts: 4,
      "Goal Diff": -6,
    },
    {
      Position: 5,
      Club: "Juventus",
      Country: "ITA",
      Participated: 22,
      Titles: 1,
      Played: 212,
      Win: 109,
      Draw: 52,
      Loss: 51,
      "Goals For": 334,
      "Goals Against": 209,
      Pts: 270,
      "Goal Diff": 125,
    },
    {
      Position: 9,
      Club: "AC Milan",
      Country: "ITA",
      Participated: 18,
      Titles: 3,
      Played: 171,
      Win: 75,
      Draw: 50,
      Loss: 46,
      "Goals For": 237,
      "Goals Against": 165,
      Pts: 200,
      "Goal Diff": 72,
    },
    {
      Position: 14,
      Club: "FC Internazionale Milano",
      Country: "ITA",
      Participated: 15,
      Titles: 1,
      Played: 129,
      Win: 58,
      Draw: 33,
      Loss: 38,
      "Goals For": 179,
      "Goals Against": 148,
      Pts: 149,
      "Goal Diff": 31,
    },
    {
      Position: 21,
      Club: "AS Roma",
      Country: "ITA",
      Participated: 11,
      Titles: 0,
      Played: 99,
      Win: 36,
      Draw: 25,
      Loss: 38,
      "Goals For": 133,
      "Goals Against": 147,
      Pts: 97,
      "Goal Diff": -14,
    },
    {
      Position: 36,
      Club: "SS Lazio",
      Country: "ITA",
      Participated: 6,
      Titles: 0,
      Played: 52,
      Win: 19,
      Draw: 15,
      Loss: 18,
      "Goals For": 79,
      "Goals Against": 68,
      Pts: 53,
      "Goal Diff": 11,
    },
    {
      Position: 40,
      Club: "SSC Napoli",
      Country: "ITA",
      Participated: 6,
      Titles: 0,
      Played: 42,
      Win: 18,
      Draw: 11,
      Loss: 13,
      "Goals For": 68,
      "Goals Against": 58,
      Pts: 47,
      "Goal Diff": 10,
    },
    {
      Position: 53,
      Club: "ACF Fiorentina",
      Country: "ITA",
      Participated: 3,
      Titles: 0,
      Played: 26,
      Win: 11,
      Draw: 8,
      Loss: 7,
      "Goals For": 39,
      "Goals Against": 34,
      Pts: 30,
      "Goal Diff": 5,
    },
    {
      Position: 61,
      Club: "Atalanta BC",
      Country: "ITA",
      Participated: 3,
      Titles: 0,
      Played: 23,
      Win: 8,
      Draw: 6,
      Loss: 9,
      "Goals For": 40,
      "Goals Against": 43,
      Pts: 22,
      "Goal Diff": -3,
    },
    {
      Position: 91,
      Club: "Parma FC",
      Country: "ITA",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 2,
      Draw: 3,
      Loss: 1,
      "Goals For": 6,
      "Goals Against": 5,
      Pts: 7,
      "Goal Diff": 1,
    },
    {
      Position: 103,
      Club: "Udinese Calcio",
      Country: "ITA",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 2,
      Draw: 1,
      Loss: 3,
      "Goals For": 10,
      "Goals Against": 12,
      Pts: 5,
      "Goal Diff": -2,
    },
    {
      Position: 108,
      Club: "Maccabi Haifa FC",
      Country: "ISR",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 2,
      Draw: 1,
      Loss: 9,
      "Goals For": 12,
      "Goals Against": 20,
      Pts: 5,
      "Goal Diff": -8,
    },
    {
      Position: 113,
      Club: "Hapoel Tel-Aviv FC",
      Country: "ISR",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 2,
      Loss: 3,
      "Goals For": 7,
      "Goals Against": 10,
      Pts: 4,
      "Goal Diff": -3,
    },
    {
      Position: 128,
      Club: "Maccabi Tel-Aviv FC",
      Country: "ISR",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 1,
      Draw: 1,
      Loss: 10,
      "Goals For": 5,
      "Goals Against": 28,
      Pts: 3,
      "Goal Diff": -23,
    },
    {
      Position: 109,
      Club: "Ferencvárosi TC",
      Country: "HUN",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 1,
      Draw: 3,
      Loss: 8,
      "Goals For": 14,
      "Goals Against": 36,
      Pts: 5,
      "Goal Diff": -22,
    },
    {
      Position: 144,
      Club: "Debreceni VSC",
      Country: "HUN",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 0,
      Loss: 6,
      "Goals For": 5,
      "Goals Against": 19,
      Pts: 0,
      "Goal Diff": -14,
    },
    {
      Position: 20,
      Club: "Olympiacos FC",
      Country: "GRE",
      Participated: 20,
      Titles: 0,
      Played: 128,
      Win: 40,
      Draw: 22,
      Loss: 66,
      "Goals For": 147,
      "Goals Against": 218,
      Pts: 102,
      "Goal Diff": -71,
    },
    {
      Position: 29,
      Club: "Panathinaikos FC",
      Country: "GRE",
      Participated: 9,
      Titles: 0,
      Played: 74,
      Win: 23,
      Draw: 18,
      Loss: 33,
      "Goals For": 76,
      "Goals Against": 104,
      Pts: 64,
      "Goal Diff": -28,
    },
    {
      Position: 68,
      Club: "AEK Athens FC",
      Country: "GRE",
      Participated: 5,
      Titles: 0,
      Played: 30,
      Win: 2,
      Draw: 12,
      Loss: 16,
      "Goals For": 19,
      "Goals Against": 49,
      Pts: 16,
      "Goal Diff": -30,
    },
    {
      Position: 3,
      Club: "FC Bayern München",
      Country: "GER",
      Participated: 25,
      Titles: 3,
      Played: 268,
      Win: 157,
      Draw: 54,
      Loss: 57,
      "Goals For": 549,
      "Goals Against": 274,
      Pts: 368,
      "Goal Diff": 275,
    },
    {
      Position: 12,
      Club: "Borussia Dortmund",
      Country: "GER",
      Participated: 16,
      Titles: 1,
      Played: 138,
      Win: 65,
      Draw: 27,
      Loss: 46,
      "Goals For": 222,
      "Goals Against": 172,
      Pts: 157,
      "Goal Diff": 50,
    },
    {
      Position: 22,
      Club: "Bayer 4 Leverkusen",
      Country: "GER",
      Participated: 12,
      Titles: 0,
      Played: 101,
      Win: 36,
      Draw: 23,
      Loss: 42,
      "Goals For": 142,
      "Goals Against": 165,
      Pts: 95,
      "Goal Diff": -23,
    },
    {
      Position: 28,
      Club: "FC Schalke 4",
      Country: "GER",
      Participated: 8,
      Titles: 0,
      Played: 66,
      Win: 26,
      Draw: 15,
      Loss: 25,
      "Goals For": 91,
      "Goals Against": 97,
      Pts: 67,
      "Goal Diff": -6,
    },
    {
      Position: 44,
      Club: "SV Werder Bremen",
      Country: "GER",
      Participated: 7,
      Titles: 0,
      Played: 46,
      Win: 16,
      Draw: 10,
      Loss: 20,
      "Goals For": 69,
      "Goals Against": 86,
      Pts: 42,
      "Goal Diff": -17,
    },
    {
      Position: 51,
      Club: "RB Leipzig",
      Country: "GER",
      Participated: 4,
      Titles: 0,
      Played: 30,
      Win: 14,
      Draw: 4,
      Loss: 12,
      "Goals For": 52,
      "Goals Against": 53,
      Pts: 32,
      "Goal Diff": -1,
    },
    {
      Position: 57,
      Club: "VfL Wolfsburg",
      Country: "GER",
      Participated: 3,
      Titles: 0,
      Played: 22,
      Win: 10,
      Draw: 3,
      Loss: 9,
      "Goals For": 29,
      "Goals Against": 29,
      Pts: 23,
      "Goal Diff": 0,
    },
    {
      Position: 64,
      Club: "VfB Stuttgart",
      Country: "GER",
      Participated: 3,
      Titles: 0,
      Played: 22,
      Win: 7,
      Draw: 5,
      Loss: 10,
      "Goals For": 26,
      "Goals Against": 34,
      Pts: 19,
      "Goal Diff": -8,
    },
    {
      Position: 73,
      Club: "VfL Borussia Mönchengladbach",
      Country: "GER",
      Participated: 3,
      Titles: 0,
      Played: 20,
      Win: 4,
      Draw: 6,
      Loss: 10,
      "Goals For": 29,
      "Goals Against": 37,
      Pts: 14,
      "Goal Diff": -8,
    },
    {
      Position: 82,
      Club: "1 FC Kaiserslautern",
      Country: "GER",
      Participated: 1,
      Titles: 0,
      Played: 8,
      Win: 4,
      Draw: 1,
      Loss: 3,
      "Goals For": 12,
      "Goals Against": 12,
      Pts: 9,
      "Goal Diff": 0,
    },
    {
      Position: 86,
      Club: "Hertha BSC Berlin",
      Country: "GER",
      Participated: 1,
      Titles: 0,
      Played: 12,
      Win: 2,
      Draw: 4,
      Loss: 6,
      "Goals For": 10,
      "Goals Against": 18,
      Pts: 8,
      "Goal Diff": -8,
    },
    {
      Position: 95,
      Club: "Hamburger SV",
      Country: "GER",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 2,
      Draw: 3,
      Loss: 7,
      "Goals For": 16,
      "Goals Against": 24,
      Pts: 7,
      "Goal Diff": -8,
    },
    {
      Position: 121,
      Club: "TSG 1899 Hoffenheim",
      Country: "GER",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 3,
      Loss: 3,
      "Goals For": 11,
      "Goals Against": 14,
      Pts: 3,
      "Goal Diff": -3,
    },
    {
      Position: 11,
      Club: "Paris Saint-Germain",
      Country: "FRA",
      Participated: 14,
      Titles: 0,
      Played: 127,
      Win: 69,
      Draw: 24,
      Loss: 34,
      "Goals For": 253,
      "Goals Against": 146,
      Pts: 162,
      "Goal Diff": 107,
    },
    {
      Position: 13,
      Club: "Olympique Lyonnais",
      Country: "FRA",
      Participated: 16,
      Titles: 0,
      Played: 136,
      Win: 58,
      Draw: 36,
      Loss: 42,
      "Goals For": 214,
      "Goals Against": 165,
      Pts: 152,
      "Goal Diff": 49,
    },
    {
      Position: 27,
      Club: "AS Monaco FC",
      Country: "FRA",
      Participated: 9,
      Titles: 0,
      Played: 78,
      Win: 30,
      Draw: 16,
      Loss: 32,
      "Goals For": 116,
      "Goals Against": 113,
      Pts: 76,
      "Goal Diff": 3,
    },
    {
      Position: 33,
      Club: "Olympique de Marseille",
      Country: "FRA",
      Participated: 10,
      Titles: 1,
      Played: 73,
      Win: 23,
      Draw: 11,
      Loss: 39,
      "Goals For": 86,
      "Goals Against": 102,
      Pts: 57,
      "Goal Diff": -16,
    },
    {
      Position: 47,
      Club: "FC Girondins de Bordeaux",
      Country: "FRA",
      Participated: 4,
      Titles: 0,
      Played: 34,
      Win: 15,
      Draw: 8,
      Loss: 11,
      "Goals For": 37,
      "Goals Against": 42,
      Pts: 38,
      "Goal Diff": -5,
    },
    {
      Position: 50,
      Club: "LOSC Lille",
      Country: "FRA",
      Participated: 7,
      Titles: 0,
      Played: 44,
      Win: 9,
      Draw: 15,
      Loss: 20,
      "Goals For": 37,
      "Goals Against": 53,
      Pts: 33,
      "Goal Diff": -16,
    },
    {
      Position: 60,
      Club: "FC Nantes",
      Country: "FRA",
      Participated: 2,
      Titles: 0,
      Played: 22,
      Win: 7,
      Draw: 8,
      Loss: 7,
      "Goals For": 27,
      "Goals Against": 26,
      Pts: 22,
      "Goal Diff": 1,
    },
    {
      Position: 70,
      Club: "AJ Auxerre",
      Country: "FRA",
      Participated: 3,
      Titles: 0,
      Played: 20,
      Win: 7,
      Draw: 1,
      Loss: 12,
      "Goals For": 16,
      "Goals Against": 30,
      Pts: 15,
      "Goal Diff": -14,
    },
    {
      Position: 78,
      Club: "RC Lens",
      Country: "FRA",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 4,
      Draw: 4,
      Loss: 4,
      "Goals For": 16,
      "Goals Against": 17,
      Pts: 12,
      "Goal Diff": -1,
    },
    {
      Position: 129,
      Club: "Montpellier Hérault SC",
      Country: "FRA",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 2,
      Loss: 4,
      "Goals For": 6,
      "Goals Against": 12,
      Pts: 2,
      "Goal Diff": -6,
    },
    {
      Position: 137,
      Club: "Stade Rennais FC",
      Country: "FRA",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 1,
      Loss: 5,
      "Goals For": 3,
      "Goals Against": 11,
      Pts: 1,
      "Goal Diff": -8,
    },
    {
      Position: 114,
      Club: "HJK Helsinki",
      Country: "FIN",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 2,
      Loss: 3,
      "Goals For": 8,
      "Goals Against": 12,
      Pts: 4,
      "Goal Diff": -4,
    },
    {
      Position: 1,
      Club: "Real Madrid CF",
      Country: "ESP",
      Participated: 26,
      Titles: 7,
      Played: 285,
      Win: 170,
      Draw: 54,
      Loss: 61,
      "Goals For": 600,
      "Goals Against": 310,
      Pts: 394,
      "Goal Diff": 290,
    },
    {
      Position: 2,
      Club: "FC Barcelona",
      Country: "ESP",
      Participated: 26,
      Titles: 4,
      Played: 271,
      Win: 158,
      Draw: 64,
      Loss: 49,
      "Goals For": 537,
      "Goals Against": 274,
      Pts: 380,
      "Goal Diff": 263,
    },
    {
      Position: 16,
      Club: "Club Atlético de Madrid",
      Country: "ESP",
      Participated: 12,
      Titles: 0,
      Played: 107,
      Win: 50,
      Draw: 31,
      Loss: 26,
      "Goals For": 145,
      "Goals Against": 99,
      Pts: 131,
      "Goal Diff": 46,
    },
    {
      Position: 17,
      Club: "Valencia CF",
      Country: "ESP",
      Participated: 12,
      Titles: 0,
      Played: 112,
      Win: 48,
      Draw: 32,
      Loss: 32,
      "Goals For": 165,
      "Goals Against": 119,
      Pts: 128,
      "Goal Diff": 46,
    },
    {
      Position: 30,
      Club: "Sevilla FC",
      Country: "ESP",
      Participated: 7,
      Titles: 0,
      Played: 54,
      Win: 24,
      Draw: 14,
      Loss: 16,
      "Goals For": 82,
      "Goals Against": 69,
      Pts: 62,
      "Goal Diff": 13,
    },
    {
      Position: 32,
      Club: "RC Deportivo La Coruña",
      Country: "ESP",
      Participated: 5,
      Titles: 0,
      Played: 58,
      Win: 23,
      Draw: 15,
      Loss: 20,
      "Goals For": 74,
      "Goals Against": 79,
      Pts: 61,
      "Goal Diff": -5,
    },
    {
      Position: 52,
      Club: "Villarreal CF",
      Country: "ESP",
      Participated: 4,
      Titles: 0,
      Played: 34,
      Win: 9,
      Draw: 13,
      Loss: 12,
      "Goals For": 35,
      "Goals Against": 43,
      Pts: 31,
      "Goal Diff": -8,
    },
    {
      Position: 76,
      Club: "Málaga CF",
      Country: "ESP",
      Participated: 1,
      Titles: 0,
      Played: 10,
      Win: 4,
      Draw: 4,
      Loss: 2,
      "Goals For": 16,
      "Goals Against": 9,
      Pts: 12,
      "Goal Diff": 7,
    },
    {
      Position: 80,
      Club: "Athletic Club",
      Country: "ESP",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 3,
      Draw: 4,
      Loss: 5,
      "Goals For": 10,
      "Goals Against": 12,
      Pts: 10,
      "Goal Diff": -2,
    },
    {
      Position: 87,
      Club: "Real Sociedad de Fútbol",
      Country: "ESP",
      Participated: 2,
      Titles: 0,
      Played: 14,
      Win: 2,
      Draw: 4,
      Loss: 8,
      "Goals For": 9,
      "Goals Against": 20,
      Pts: 8,
      "Goal Diff": -11,
    },
    {
      Position: 93,
      Club: "RC Celta de Vigo",
      Country: "ESP",
      Participated: 1,
      Titles: 0,
      Played: 8,
      Win: 2,
      Draw: 3,
      Loss: 3,
      "Goals For": 9,
      "Goals Against": 11,
      Pts: 7,
      "Goal Diff": -2,
    },
    {
      Position: 99,
      Club: "RCD Mallorca",
      Country: "ESP",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 3,
      Draw: 0,
      Loss: 3,
      "Goals For": 4,
      "Goals Against": 9,
      Pts: 6,
      "Goal Diff": -5,
    },
    {
      Position: 107,
      Club: "Real Betis Balompié",
      Country: "ESP",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 2,
      Draw: 1,
      Loss: 3,
      "Goals For": 3,
      "Goals Against": 7,
      Pts: 5,
      "Goal Diff": -4,
    },
    {
      Position: 4,
      Club: "Manchester United",
      Country: "ENG",
      Participated: 24,
      Titles: 2,
      Played: 236,
      Win: 124,
      Draw: 58,
      Loss: 54,
      "Goals For": 399,
      "Goals Against": 228,
      Pts: 306,
      "Goal Diff": 171,
    },
    {
      Position: 6,
      Club: "Chelsea FC",
      Country: "ENG",
      Participated: 18,
      Titles: 2,
      Played: 183,
      Win: 93,
      Draw: 51,
      Loss: 39,
      "Goals For": 314,
      "Goals Against": 166,
      Pts: 237,
      "Goal Diff": 148,
    },
    {
      Position: 8,
      Club: "Arsenal FC",
      Country: "ENG",
      Participated: 19,
      Titles: 0,
      Played: 177,
      Win: 83,
      Draw: 41,
      Loss: 53,
      "Goals For": 281,
      "Goals Against": 205,
      Pts: 207,
      "Goal Diff": 76,
    },
    {
      Position: 10,
      Club: "Liverpool FC",
      Country: "ENG",
      Participated: 14,
      Titles: 2,
      Played: 138,
      Win: 71,
      Draw: 34,
      Loss: 33,
      "Goals For": 241,
      "Goals Against": 134,
      Pts: 176,
      "Goal Diff": 107,
    },
    {
      Position: 18,
      Club: "Manchester City FC",
      Country: "ENG",
      Participated: 11,
      Titles: 0,
      Played: 96,
      Win: 53,
      Draw: 16,
      Loss: 27,
      "Goals For": 195,
      "Goals Against": 118,
      Pts: 122,
      "Goal Diff": 77,
    },
    {
      Position: 39,
      Club: "Tottenham Hotspur",
      Country: "ENG",
      Participated: 5,
      Titles: 0,
      Played: 45,
      Win: 20,
      Draw: 9,
      Loss: 16,
      "Goals For": 81,
      "Goals Against": 67,
      Pts: 49,
      "Goal Diff": 14,
    },
    {
      Position: 65,
      Club: "Leeds United AFC",
      Country: "ENG",
      Participated: 1,
      Titles: 0,
      Played: 16,
      Win: 6,
      Draw: 5,
      Loss: 5,
      "Goals For": 24,
      "Goals Against": 21,
      Pts: 17,
      "Goal Diff": 3,
    },
    {
      Position: 67,
      Club: "Newcastle United FC",
      Country: "ENG",
      Participated: 2,
      Titles: 0,
      Played: 18,
      Win: 7,
      Draw: 2,
      Loss: 9,
      "Goals For": 23,
      "Goals Against": 29,
      Pts: 16,
      "Goal Diff": -6,
    },
    {
      Position: 77,
      Club: "Leicester City FC",
      Country: "ENG",
      Participated: 1,
      Titles: 0,
      Played: 10,
      Win: 5,
      Draw: 2,
      Loss: 3,
      "Goals For": 11,
      "Goals Against": 10,
      Pts: 12,
      "Goal Diff": 1,
    },
    {
      Position: 122,
      Club: "Blackburn Rovers FC",
      Country: "ENG",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 1,
      Loss: 4,
      "Goals For": 5,
      "Goals Against": 8,
      Pts: 3,
      "Goal Diff": -3,
    },
    {
      Position: 58,
      Club: "F.C. Copenhagen",
      Country: "DEN",
      Participated: 4,
      Titles: 0,
      Played: 26,
      Win: 8,
      Draw: 7,
      Loss: 11,
      "Goals For": 23,
      "Goals Against": 30,
      Pts: 23,
      "Goal Diff": -7,
    },
    {
      Position: 88,
      Club: "Aalborg BK",
      Country: "DEN",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 2,
      Draw: 4,
      Loss: 6,
      "Goals For": 14,
      "Goals Against": 26,
      Pts: 8,
      "Goal Diff": -12,
    },
    {
      Position: 132,
      Club: "FC Midtjylland",
      Country: "DEN",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 2,
      Loss: 4,
      "Goals For": 4,
      "Goals Against": 13,
      Pts: 2,
      "Goal Diff": -9,
    },
    {
      Position: 135,
      Club: "Brøndby IF",
      Country: "DEN",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 0,
      Loss: 5,
      "Goals For": 4,
      "Goals Against": 18,
      Pts: 2,
      "Goal Diff": -14,
    },
    {
      Position: 141,
      Club: "FC Nordsjælland",
      Country: "DEN",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 1,
      Loss: 5,
      "Goals For": 4,
      "Goals Against": 22,
      Pts: 1,
      "Goal Diff": -18,
    },
    {
      Position: 46,
      Club: "AC Sparta Praha",
      Country: "CZE",
      Participated: 7,
      Titles: 0,
      Played: 56,
      Win: 13,
      Draw: 15,
      Loss: 28,
      "Goals For": 57,
      "Goals Against": 86,
      Pts: 41,
      "Goal Diff": -29,
    },
    {
      Position: 79,
      Club: "FC Viktoria Plzeň",
      Country: "CZE",
      Participated: 3,
      Titles: 0,
      Played: 18,
      Win: 4,
      Draw: 3,
      Loss: 11,
      "Goals For": 17,
      "Goals Against": 44,
      Pts: 11,
      "Goal Diff": -27,
    },
    {
      Position: 100,
      Club: "SK Slavia Praha",
      Country: "CZE",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 1,
      Draw: 4,
      Loss: 7,
      "Goals For": 9,
      "Goals Against": 26,
      Pts: 6,
      "Goal Diff": -17,
    },
    {
      Position: 71,
      Club: "APOEL FC",
      Country: "CYP",
      Participated: 4,
      Titles: 0,
      Played: 28,
      Win: 3,
      Draw: 9,
      Loss: 16,
      "Goals For": 16,
      "Goals Against": 51,
      Pts: 15,
      "Goal Diff": -35,
    },
    {
      Position: 102,
      Club: "Anorthosis Famagusta FC",
      Country: "CYP",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 3,
      Loss: 2,
      "Goals For": 8,
      "Goals Against": 8,
      Pts: 5,
      "Goal Diff": 0,
    },
    {
      Position: 66,
      Club: "GNK Dinamo Zagreb",
      Country: "CRO",
      Participated: 7,
      Titles: 0,
      Played: 42,
      Win: 5,
      Draw: 7,
      Loss: 30,
      "Goals For": 29,
      "Goals Against": 92,
      Pts: 17,
      "Goal Diff": -63,
    },
    {
      Position: 94,
      Club: "HNK Hajduk Split",
      Country: "CRO",
      Participated: 1,
      Titles: 0,
      Played: 8,
      Win: 2,
      Draw: 3,
      Loss: 3,
      "Goals For": 5,
      "Goals Against": 10,
      Pts: 7,
      "Goal Diff": -5,
    },
    {
      Position: 101,
      Club: "PFC Ludogorets 1945",
      Country: "BUL",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 1,
      Draw: 4,
      Loss: 7,
      "Goals For": 11,
      "Goals Against": 29,
      Pts: 6,
      "Goal Diff": -18,
    },
    {
      Position: 146,
      Club: "PFC Levski Sofia",
      Country: "BUL",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 0,
      Loss: 6,
      "Goals For": 1,
      "Goals Against": 17,
      Pts: 0,
      "Goal Diff": -16,
    },
    {
      Position: 72,
      Club: "FC BATE Borisov",
      Country: "BLR",
      Participated: 5,
      Titles: 0,
      Played: 30,
      Win: 4,
      Draw: 7,
      Loss: 19,
      "Goals For": 21,
      "Goals Against": 73,
      Pts: 15,
      "Goal Diff": -52,
    },
    {
      Position: 43,
      Club: "RSC Anderlecht",
      Country: "BEL",
      Participated: 12,
      Titles: 0,
      Played: 78,
      Win: 13,
      Draw: 20,
      Loss: 45,
      "Goals For": 65,
      "Goals Against": 150,
      Pts: 46,
      "Goal Diff": -85,
    },
    {
      Position: 48,
      Club: "Club Brugge",
      Country: "BEL",
      Participated: 9,
      Titles: 0,
      Played: 54,
      Win: 11,
      Draw: 15,
      Loss: 28,
      "Goals For": 47,
      "Goals Against": 89,
      Pts: 37,
      "Goal Diff": -42,
    },
    {
      Position: 90,
      Club: "KRC Genk",
      Country: "BEL",
      Participated: 3,
      Titles: 0,
      Played: 18,
      Win: 0,
      Draw: 8,
      Loss: 10,
      "Goals For": 9,
      "Goals Against": 45,
      Pts: 8,
      "Goal Diff": -36,
    },
    {
      Position: 92,
      Club: "KAA Gent",
      Country: "BEL",
      Participated: 1,
      Titles: 0,
      Played: 8,
      Win: 3,
      Draw: 1,
      Loss: 4,
      "Goals For": 10,
      "Goals Against": 11,
      Pts: 7,
      "Goal Diff": -1,
    },
    {
      Position: 112,
      Club: "R. Standard de Liège",
      Country: "BEL",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 2,
      Loss: 3,
      "Goals For": 7,
      "Goals Against": 9,
      Pts: 4,
      "Goal Diff": -2,
    },
    {
      Position: 138,
      Club: "K. Lierse SK",
      Country: "BEL",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 1,
      Loss: 5,
      "Goals For": 3,
      "Goals Against": 12,
      Pts: 1,
      "Goal Diff": -9,
    },
    {
      Position: 134,
      Club: "Qarabağ FK",
      Country: "AZE",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 2,
      Loss: 4,
      "Goals For": 2,
      "Goals Against": 14,
      Pts: 2,
      "Goal Diff": -12,
    },
    {
      Position: 63,
      Club: "FC Salzburg",
      Country: "AUT",
      Participated: 4,
      Titles: 0,
      Played: 24,
      Win: 7,
      Draw: 6,
      Loss: 11,
      "Goals For": 38,
      "Goals Against": 42,
      Pts: 20,
      "Goal Diff": -4,
    },
    {
      Position: 69,
      Club: "SK Sturm Graz",
      Country: "AUT",
      Participated: 3,
      Titles: 0,
      Played: 24,
      Win: 7,
      Draw: 2,
      Loss: 15,
      "Goals For": 20,
      "Goals Against": 53,
      Pts: 16,
      "Goal Diff": -33,
    },
    {
      Position: 117,
      Club: "FK Austria Wien",
      Country: "AUT",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 2,
      Loss: 3,
      "Goals For": 5,
      "Goals Against": 10,
      Pts: 4,
      "Goal Diff": -5,
    },
    {
      Position: 136,
      Club: "SK Rapid Wien",
      Country: "AUT",
      Participated: 2,
      Titles: 0,
      Played: 12,
      Win: 0,
      Draw: 2,
      Loss: 10,
      "Goals For": 5,
      "Goals Against": 27,
      Pts: 2,
      "Goal Diff": -22,
    },
  ];
  return (
    <div className="App">
      <header>
        <VictoryChart horizontal>
          <VictoryBar
            width={400}
            data={countryTitles}
            // data accessor for x values
            x="Club"
            // data accessor for y values
            y="Pts"
            style={{ labels: { fontSize: 1 } }}
            events={[
              {
                target: "data",
                childName: "Bar-1",
                eventHandlers: {
                  onClick: () => ({
                    target: "data",
                    mutation: () => ({ style: { fill: "orange" } }),
                  }),
                },
              },
            ]}
          />
          <VictoryAxis
            style={{
              tickLabels: { fontSize: 5 },
            }}
          />
          <VictoryAxis
            dependentAxis
            style={{
              tickLabels: { fontSize: 5 },
            }}
          />
        </VictoryChart>
      </header>
    </div>
  );
}

export default App;
