import logo from "./logo.svg";
import "./App.css";
import React from "react";
import { render } from "react-dom";
import { VictoryBar, VictoryChart, VictoryAxis } from "victory";

function App() {
  const countryTitles = [
    {
      FIELD1: "1",
      Country: "Spain",
      Participated: 100,
      Titles: 11,
      Played: 977,
      Win: 498,
      Draw: 239,
      Loss: 240,
      "Goals For": 1689,
      "Goals Against": 1061,
      Pts: 1235,
      "Goal Diff": 628,
    },
    {
      FIELD1: "2",
      Country: "England",
      Participated: 96,
      Titles: 6,
      Played: 925,
      Win: 463,
      Draw: 219,
      Loss: 243,
      "Goals For": 1574,
      "Goals Against": 986,
      Pts: 1145,
      "Goal Diff": 588,
    },
    {
      FIELD1: "3",
      Country: "Italy",
      Participated: 86,
      Titles: 5,
      Played: 766,
      Win: 338,
      Draw: 204,
      Loss: 224,
      "Goals For": 1125,
      "Goals Against": 889,
      Pts: 880,
      "Goal Diff": 236,
    },
    {
      FIELD1: "4",
      Country: "Germany",
      Participated: 86,
      Titles: 4,
      Played: 751,
      Win: 343,
      Draw: 158,
      Loss: 250,
      "Goals For": 1258,
      "Goals Against": 1015,
      Pts: 844,
      "Goal Diff": 243,
    },
    {
      FIELD1: "5",
      Country: "France",
      Participated: 69,
      Titles: 1,
      Played: 558,
      Win: 222,
      Draw: 126,
      Loss: 210,
      "Goals For": 811,
      "Goals Against": 717,
      Pts: 570,
      "Goal Diff": 94,
    },
    {
      FIELD1: "6",
      Country: "Portugal",
      Participated: 54,
      Titles: 1,
      Played: 402,
      Win: 151,
      Draw: 90,
      Loss: 161,
      "Goals For": 494,
      "Goals Against": 539,
      Pts: 392,
      "Goal Diff": -45,
    },
    {
      FIELD1: "7",
      Country: "Netherlands",
      Participated: 42,
      Titles: 1,
      Played: 302,
      Win: 100,
      Draw: 80,
      Loss: 122,
      "Goals For": 359,
      "Goals Against": 408,
      Pts: 280,
      "Goal Diff": -49,
    },
    {
      FIELD1: "8",
      Country: "Russia",
      Participated: 43,
      Titles: 0,
      Played: 286,
      Win: 71,
      Draw: 68,
      Loss: 147,
      "Goals For": 306,
      "Goals Against": 464,
      Pts: 210,
      "Goal Diff": -158,
    },
    {
      FIELD1: "9",
      Country: "Greece",
      Participated: 34,
      Titles: 0,
      Played: 232,
      Win: 65,
      Draw: 52,
      Loss: 115,
      "Goals For": 242,
      "Goals Against": 371,
      Pts: 182,
      "Goal Diff": -129,
    },
    {
      FIELD1: "10",
      Country: "Ukraine",
      Participated: 34,
      Titles: 0,
      Played: 227,
      Win: 65,
      Draw: 52,
      Loss: 110,
      "Goals For": 277,
      "Goals Against": 370,
      Pts: 182,
      "Goal Diff": -93,
    },
    {
      FIELD1: "11",
      Country: "Turkey",
      Participated: 33,
      Titles: 0,
      Played: 224,
      Win: 54,
      Draw: 49,
      Loss: 121,
      "Goals For": 212,
      "Goals Against": 408,
      Pts: 157,
      "Goal Diff": -196,
    },
    {
      FIELD1: "12",
      Country: "Belguim",
      Participated: 27,
      Titles: 0,
      Played: 170,
      Win: 28,
      Draw: 47,
      Loss: 95,
      "Goals For": 141,
      "Goals Against": 316,
      Pts: 103,
      "Goal Diff": -175,
    },
    {
      FIELD1: "13",
      Country: "Scotland",
      Participated: 20,
      Titles: 0,
      Played: 128,
      Win: 30,
      Draw: 33,
      Loss: 65,
      "Goals For": 124,
      "Goals Against": 210,
      Pts: 93,
      "Goal Diff": -86,
    },
    {
      FIELD1: "14",
      Country: "Switzerland",
      Participated: 14,
      Titles: 0,
      Played: 96,
      Win: 26,
      Draw: 20,
      Loss: 50,
      "Goals For": 99,
      "Goals Against": 172,
      Pts: 72,
      "Goal Diff": -73,
    },
    {
      FIELD1: "15",
      Country: "Norway",
      Participated: 12,
      Titles: 0,
      Played: 80,
      Win: 20,
      Draw: 18,
      Loss: 42,
      "Goals For": 101,
      "Goals Against": 143,
      Pts: 58,
      "Goal Diff": -42,
    },
    {
      FIELD1: "16",
      Country: "Czech Republic",
      Participated: 12,
      Titles: 0,
      Played: 86,
      Win: 18,
      Draw: 22,
      Loss: 46,
      "Goals For": 83,
      "Goals Against": 156,
      Pts: 58,
      "Goal Diff": -73,
    },
    {
      FIELD1: "17",
      Country: "Austria",
      Participated: 10,
      Titles: 0,
      Played: 66,
      Win: 15,
      Draw: 12,
      Loss: 39,
      "Goals For": 68,
      "Goals Against": 132,
      Pts: 42,
      "Goal Diff": -64,
    },
    {
      FIELD1: "18",
      Country: "Romania",
      Participated: 12,
      Titles: 0,
      Played: 72,
      Win: 11,
      Draw: 19,
      Loss: 42,
      "Goals For": 61,
      "Goals Against": 116,
      Pts: 41,
      "Goal Diff": -55,
    },
    {
      FIELD1: "19",
      Country: "Denmark",
      Participated: 9,
      Titles: 0,
      Played: 56,
      Win: 11,
      Draw: 14,
      Loss: 31,
      "Goals For": 49,
      "Goals Against": 109,
      Pts: 36,
      "Goal Diff": -60,
    },
    {
      FIELD1: "20",
      Country: "Swedend",
      Participated: 9,
      Titles: 0,
      Played: 56,
      Win: 13,
      Draw: 7,
      Loss: 36,
      "Goals For": 46,
      "Goals Against": 119,
      Pts: 33,
      "Goal Diff": -73,
    },
    {
      FIELD1: "21",
      Country: "Croatia",
      Participated: 8,
      Titles: 0,
      Played: 50,
      Win: 7,
      Draw: 10,
      Loss: 33,
      "Goals For": 34,
      "Goals Against": 102,
      Pts: 24,
      "Goal Diff": -68,
    },
    {
      FIELD1: "22",
      Country: "Cyprus",
      Participated: 5,
      Titles: 0,
      Played: 34,
      Win: 4,
      Draw: 12,
      Loss: 18,
      "Goals For": 24,
      "Goals Against": 59,
      Pts: 20,
      "Goal Diff": -35,
    },
    {
      FIELD1: "23",
      Country: "Belarus",
      Participated: 5,
      Titles: 0,
      Played: 30,
      Win: 4,
      Draw: 7,
      Loss: 19,
      "Goals For": 21,
      "Goals Against": 73,
      Pts: 15,
      "Goal Diff": -52,
    },
    {
      FIELD1: "24",
      Country: "Israel",
      Participated: 5,
      Titles: 0,
      Played: 30,
      Win: 4,
      Draw: 4,
      Loss: 22,
      "Goals For": 24,
      "Goals Against": 58,
      Pts: 12,
      "Goal Diff": -34,
    },
    {
      FIELD1: "25",
      Country: "Poland",
      Participated: 3,
      Titles: 0,
      Played: 20,
      Win: 4,
      Draw: 4,
      Loss: 12,
      "Goals For": 20,
      "Goals Against": 45,
      Pts: 12,
      "Goal Diff": -25,
    },
    {
      FIELD1: "26",
      Country: "SLovenia",
      Participated: 3,
      Titles: 0,
      Played: 18,
      Win: 1,
      Draw: 7,
      Loss: 10,
      "Goals For": 9,
      "Goals Against": 41,
      Pts: 9,
      "Goal Diff": -32,
    },
    {
      FIELD1: "27",
      Country: "Serbia",
      Participated: 4,
      Titles: 0,
      Played: 24,
      Win: 2,
      Draw: 4,
      Loss: 18,
      "Goals For": 13,
      "Goals Against": 58,
      Pts: 8,
      "Goal Diff": -45,
    },
    {
      FIELD1: "28",
      Country: "Bulgaria",
      Participated: 3,
      Titles: 0,
      Played: 18,
      Win: 1,
      Draw: 4,
      Loss: 13,
      "Goals For": 12,
      "Goals Against": 46,
      Pts: 6,
      "Goal Diff": -34,
    },
    {
      FIELD1: "29",
      Country: "Moldova",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 2,
      Draw: 1,
      Loss: 3,
      "Goals For": 7,
      "Goals Against": 11,
      Pts: 5,
      "Goal Diff": -4,
    },
    {
      FIELD1: "30",
      Country: "Hungary",
      Participated: 3,
      Titles: 0,
      Played: 18,
      Win: 1,
      Draw: 3,
      Loss: 14,
      "Goals For": 19,
      "Goals Against": 55,
      Pts: 5,
      "Goal Diff": -36,
    },
    {
      FIELD1: "31",
      Country: "Slovakia",
      Participated: 3,
      Titles: 0,
      Played: 18,
      Win: 1,
      Draw: 3,
      Loss: 14,
      "Goals For": 10,
      "Goals Against": 41,
      Pts: 5,
      "Goal Diff": -31,
    },
    {
      FIELD1: "32",
      Country: "Finland",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 1,
      Draw: 2,
      Loss: 3,
      "Goals For": 8,
      "Goals Against": 12,
      Pts: 4,
      "Goal Diff": -4,
    },
    {
      FIELD1: "33",
      Country: "Kazakhstan",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 4,
      Loss: 2,
      "Goals For": 5,
      "Goals Against": 11,
      Pts: 4,
      "Goal Diff": -6,
    },
    {
      FIELD1: "34",
      Country: "Azerbaijan",
      Participated: 1,
      Titles: 0,
      Played: 6,
      Win: 0,
      Draw: 2,
      Loss: 4,
      "Goals For": 2,
      "Goals Against": 14,
      Pts: 2,
      "Goal Diff": -12,
    },
  ];

  return (
    <div className="App">
      <header>
        <VictoryChart horizontal>
          <VictoryBar
            width={400}
            data={countryTitles}
            // data accessor for x values
            x="FIELD1"
            // data accessor for y values
            y="Participated"
            style={{ labels: { fontSize: 1 } }}
            events={[
              {
                target: "data",
                childName: "Bar-1",
                eventHandlers: {
                  onClick: () => ({
                    target: "data",
                    // mutation: () => ({ style: { fill: "orange" } }),
                    href: "./clubs",
                  }),
                },
              },
            ]}
          />
          <VictoryAxis
            style={{
              tickLabels: { fontSize: 5 },
            }}
          />
          <VictoryAxis
            dependentAxis
            style={{
              tickLabels: { fontSize: 5 },
            }}
          />
        </VictoryChart>
      </header>
    </div>
  );
}

export default App;
